### ISSUE TITLE
Hissp: It's Python with a *Lissp*

### ISSUE THREAD

**Issue by gilch** [vindarel/languages-that-compile-to-python#14]
Have you seen [Hissp](https://github.com/gilch/hissp) yet?

**Comment by vindarel** [comment]
Oh, yes, it deserves its entry.

**Comment by vindarel** [comment]
done https://github.com/vindarel/languages-that-compile-to-python/commit/dc0ed54cb06bd1a414249f7feecf2d1ec3e467c6

**Comment by gilch** [comment]
section is missing link at the top
