### ISSUE TITLE
Pixie is (not !) discontinued

### ISSUE THREAD

**Issue by vindarel** [vindarel/languages-that-compile-to-python#7]
https://www.reddit.com/r/programming/comments/5ol0gp/pixie_a_small_fast_native_lisp_with_magical_powers/

> I'm the original author of pixie, and yeah, I'm a bit surprised to see this hit HN today. It should be mentioned that I put about a year of work into this language, and then moved on about a year or so ago. One of the biggest reasons for my doing so is that I accomplished what I was looking for: a fast lisp that favored immutability and was built on the RPython toolchain (same as PyPy). But in the end the lack of supporting libraries and ecosystem became a battle I no longer wanted to fight.

> Another goal I had was to see how far I could push immutability into the JIT. I learned a lot along the way, but it turns out that the RPython JITs aren't really that happy with VMs that are 99.99% pure. At one point I had a almost 100% immutable VM running for Pixie...as in each instruction executed created a new instance of the VM. It worked, but the JIT generated by RPython wasn't exactly happy with that execution model. There was so much noise in the maintenance of the immutable structures that the JIT couldn't figure out how to remove them all, and even when it could the JIT pauses were too high.

> So anyways, after pouring 4 hours a day of my spare time into Pixie for a full year, I needed to move on.

> Some other developers have commit rights and have pushed it along a bit, but I think it's somewhat a language looking for usecase.

> And these days ClojureScript on Node.js could probably be made to handle most peoples needs.

**Comment by halgari** [comment]
Not true (I'm the author of both this post and Pixie). If it's useful to people then I hope it's maintained, and that work continues forward. The idea that it has to be discontinued simply because the original author has moved on is incorrect.

**Comment by vindarel** [comment]
You're right. It was a bit pessimistic to read you but I can't claim the project is discontinued, sorry. 
The content of the readme didn't change, I'll close this issue and edit its title.

**Comment by g3ntleman** [comment]
I'd be willing to give it a try and fix things on the way. There seems to be some momentum, so it would be cool for the committers to merge the existing enhancements. Making it build again on the major platforms should be the first step, IMHO.
